# Generated by Django 4.1 on 2022-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
