# Generated by Django 4.1 on 2022-08-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_author_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='keywords',
            field=models.CharField(default=models.CharField(max_length=500, verbose_name='Song Title'), max_length=5000, verbose_name='Keywords'),
        ),
    ]
